import { Zone, ZoneId } from "@/types";

export const ZONES: Record<ZoneId, Zone> = {
  pepperoni: {
    id: "pepperoni",
    name: "DEX & Trading",
    topping: "Pepperoni",
    toppingEmoji: "🍕",
    color: "#E63946",
    colorRgb: "230, 57, 70",
    description: "Swaps, perps, and all things trading",
    protocol: "Kuru DEX",
    sliceImage: "/assets/pepperoni.png",
    sliceImageHot: "/assets/pepperoni_hot.png",
    barClass: "bar-pep",
    sparkColor: "#ef4444",
    displayName: "pepperoni",
  },
  mushroom: {
    id: "mushroom",
    name: "Lending & Staking",
    topping: "Mushroom",
    toppingEmoji: "🍄",
    color: "#7C3AED",
    colorRgb: "124, 58, 237",
    description: "Lending, staking, yield farming",
    protocol: "aPriori",
    sliceImage: "/assets/mushroom.png",
    sliceImageHot: "/assets/mushroom_hot.png",
    barClass: "bar-mush",
    sparkColor: "#f5c800",
    displayName: "mushrooms",
  },
  pineapple: {
    id: "pineapple",
    name: "Meme & Launch",
    topping: "Pineapple",
    toppingEmoji: "🍍",
    color: "#D4A017",
    colorRgb: "212, 160, 23",
    description: "Meme coins and token launches",
    protocol: "Meme Coins",
    sliceImage: "/assets/pineapple.png",
    sliceImageHot: "/assets/pineapple_hot.png",
    barClass: "bar-pine",
    sparkColor: "#22c55e",
    displayName: "pineapple",
  },
  olive: {
    id: "olive",
    name: "Infrastructure",
    topping: "Olive",
    toppingEmoji: "🫒",
    color: "#0891B2",
    colorRgb: "8, 145, 178",
    description: "Oracles, bridges, and infra",
    protocol: "Ambient Finance",
    sliceImage: "/assets/olives.png",
    sliceImageHot: "/assets/olives_hot.png",
    barClass: "bar-oliv",
    sparkColor: "#f97316",
    displayName: "olives",
  },
  anchovy: {
    id: "anchovy",
    name: "Gaming & Social",
    topping: "Anchovy",
    toppingEmoji: "🐟",
    color: "#EA580C",
    colorRgb: "234, 88, 12",
    description: "Games, social, AI, and NFTs",
    protocol: "Bean Exchange",
    sliceImage: "/assets/anchovies.png",
    sliceImageHot: "/assets/anchovies_hot.png",
    barClass: "bar-anch",
    sparkColor: "#64748b",
    displayName: "anchovies",
  },
};

export const ZONE_LIST: Zone[] = Object.values(ZONES);
export const ZONE_IDS: ZoneId[] = Object.keys(ZONES) as ZoneId[];
